### ISSUE TITLE
ImportError: No module named defaults

### ISSUE THREAD

**Issue by Ghostavio** [toranb/ember-django-pagination#3]
```
Traceback (most recent call last):
  File "/Users/gustavo/webapps/krakenEnv/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/Users/gustavo/webapps/krakenEnv/lib/python2.7/site-packages/django/middleware/common.py", line 72, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Users/gustavo/webapps/krakenEnv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 619, in is_valid_path
    resolve(path, urlconf)
  File "/Users/gustavo/webapps/krakenEnv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 494, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Users/gustavo/webapps/krakenEnv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/Users/gustavo/webapps/krakenEnv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/gustavo/webapps/krakenEnv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/gustavo/webapps/gus/ember-django-pagination/ember/urls.py", line 5, in <module>
    url(r'^people', include('ember.person.urls', namespace='person')),
  File "/Users/gustavo/webapps/krakenEnv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/gustavo/webapps/gus/ember-django-pagination/ember/person/urls.py", line 3, in <module>
    from django.conf.urls.defaults import patterns, url, include
ImportError: No module named defaults
```

when trying to run `python manage.py runserver`

**Comment by toranb** [comment]
Ah my guess is I need to lock this example down to django 1.6.x

**Comment by toranb** [comment]
fixed :)

I got a fully working version - could still use an update of the client deps if you are using the latest ember-data / DRF

This _works_ now so I'll close it down but the example is dated when you compare it to the latest ember-cli django /ember-data adapter
